sudo: required
language: generic
services:
  - docker # telling travisCI we need a docker copy ready to go

before_install:
  - docker build -t abhi90g/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhi90g/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-754789248719"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY