language: generic
sudo: required
services:
  - docker # telling travisCI we need a docker copy ready to go

before_install:
  - docker build -t abhi90g/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhi90g/docker-react npm run test